servers:
  group-id: kvStoreRaftGroup
  peers:
    - id: 1
      address: kv-peer-1:8081
    - id: 2
      address: kv-peer-2:8082
    - id: 3
      address: kv-peer-3:8083
    # - id: 4
    #   address: kv-peer-4:8084
    # - id: 5
    #   address: kv-peer-5:8085
#    - id: 6
#      address: kv-peer-6:8086
#    - id: 7
#      address: kv-peer-7:8087
consensus:
  protocol: ${CLIENT_CONSENSUS_PROTOCOL:raft}