servers:
  group-id: kvStoreRaftGroup
  peers:
    - id: 1
      address: kv-peer-1:8081
    - id: 2
      address: kv-peer-2:8082
    - id: 3
      address: kv-peer-3:8083
consensus:
  protocol: ${CLIENT_CONSENSUS_PROTOCOL:paxos}