version: '3.8'

services:
  client:
    build: ../kv-store-client
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      CLIENT_CONSENSUS_PROTOCOL: paxos
  
  kv-peer-1:
    build: ../kv-store
    ports:
      - "8081:8081"
    networks:
      - backend
    volumes:
      - kv-peer-1:/var/lib/kvstore/data
    environment:
      KV_STORE_PROTOCOL: "paxos"
      RATIS_KV_PEER_ID: 1
      RATIS_KV_PORT: 8081
      RATIS_KV_PEERS: 1:localhost:8081,2:kv-peer-2:8082,3:kv-peer-3:8083 #,4:kv-peer-4:8084,5:kv-peer-5:8085,6:kv-peer-6:8086,7:kv-peer-7:8087
      RATIS_KV_GROUP_ID: kvStoreRaftGroup
      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
  kv-peer-2:
    build: ../kv-store
    ports:
      - "8082:8082"
    networks:
      - backend
    volumes:
      - kv-peer-2:/var/lib/kvstore/data
    environment:
      KV_STORE_PROTOCOL: "paxos"
      RATIS_KV_PEER_ID: 2
      RATIS_KV_PORT: 8082
      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:localhost:8082,3:kv-peer-3:8083 #,4:kv-peer-4:8084,5:kv-peer-5:8085,6:kv-peer-6:8086,7:kv-peer-7:8087
      RATIS_KV_GROUP_ID: kvStoreRaftGroup
      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
  kv-peer-3:
    build: ../kv-store
    ports:
      - "8083:8083"
    networks:
      - backend
    volumes:
      - kv-peer-3:/var/lib/kvstore/data
    environment:
      KV_STORE_PROTOCOL: "paxos"
      RATIS_KV_PEER_ID: 3
      RATIS_KV_PORT: 8083
      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:kv-peer-2:8082,3:localhost:8083 #,4:kv-peer-4:8084,5:kv-peer-5:8085,6:kv-peer-6:8086,7:kv-peer-7:8087
      RATIS_KV_GROUP_ID: kvStoreRaftGroup
      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data

#  kv-peer-4:
#    build: ../kv-store
#    ports:
#      - "8084:8084"
#    networks:
#      - backend
#    volumes:
#      - kv-peer-4:/var/lib/kvstore/data
#    environment:
#      KV_STORE_PROTOCOL: "raft"
#      RATIS_KV_PEER_ID: 4
#      RATIS_KV_PORT: 8084
#      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:kv-peer-2:8082,3:kv-peer-3:8083,4:localhost:8084,5:kv-peer-5:8085,6:kv-peer-6:8086,7:kv-peer-7:8087
#      RATIS_KV_GROUP_ID: kvStoreRaftGroup
#      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
#  kv-peer-5:
#    build: ../kv-store
#    ports:
#      - "8085:8085"
#    networks:
#      - backend
#    volumes:
#      - kv-peer-5:/var/lib/kvstore/data
#    environment:
#      KV_STORE_PROTOCOL: "raft"
#      RATIS_KV_PEER_ID: 5
#      RATIS_KV_PORT: 8085
#      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:kv-peer-2:8082,3:kv-peer-3:8083,4:kv-peer-4:8084,5:localhost:8085,6:kv-peer-6:8086,7:kv-peer-7:8087
#      RATIS_KV_GROUP_ID: kvStoreRaftGroup
#      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
#
#  kv-peer-6:
#    build: ../kv-store
#    ports:
#      - "8086:8086"
#    networks:
#      - backend
#    volumes:
#      - kv-peer-6:/var/lib/kvstore/data
#    environment:
#      KV_STORE_PROTOCOL: "raft"
#      RATIS_KV_PEER_ID: 6
#      RATIS_KV_PORT: 8086
#      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:kv-peer-2:8082,3:kv-peer-3:8083,4:kv-peer-4:8084,5:kv-peer-5:8085,6:localhost:8086,7:kv-peer-7:8087
#      RATIS_KV_GROUP_ID: kvStoreRaftGroup
#      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
#  kv-peer-7:
#    build: ../kv-store
#    ports:
#      - "8087:8087"
#    networks:
#      - backend
#    volumes:
#      - kv-peer-7:/var/lib/kvstore/data
#    environment:
#      KV_STORE_PROTOCOL: "raft"
#      RATIS_KV_PEER_ID: 7
#      RATIS_KV_PORT: 8087
#      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:kv-peer-2:8082,3:kv-peer-3:8083,4:kv-peer-4:8084,5:kv-peer-5:8085,6:kv-peer-6:8086,7:localhost:8087
#      RATIS_KV_GROUP_ID: kvStoreRaftGroup
#      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
volumes:
  kv-peer-1:
  kv-peer-2:
  kv-peer-3:
  kv-peer-4:
  kv-peer-5:
  kv-peer-6:
  kv-peer-7:
networks:
  backend:

