version: '3.8'

services:
  client:
    build: ../kv-store-client
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      CLIENT_CONSENSUS_PROTOCOL: paxos
  
  kv-peer-1:
    build: ../kv-store
    ports:
      - "8081:8081"
    networks:
      - backend
    volumes:
      - kv-peer-1:/var/lib/kvstore/data
    environment:
      KV_STORE_PROTOCOL: "paxos"
      RATIS_KV_PEER_ID: 1
      RATIS_KV_PORT: 8081
      RATIS_KV_PEERS: 1:localhost:8081,2:kv-peer-2:8082,3:kv-peer-3:8083
      RATIS_KV_GROUP_ID: kvStoreRaftGroup
      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
  kv-peer-2:
    build: ../kv-store
    ports:
      - "8082:8082"
    networks:
      - backend
    volumes:
      - kv-peer-2:/var/lib/kvstore/data
    environment:
      KV_STORE_PROTOCOL: "paxos"
      RATIS_KV_PEER_ID: 2
      RATIS_KV_PORT: 8082
      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:localhost:8082,3:kv-peer-3:8083
      RATIS_KV_GROUP_ID: kvStoreRaftGroup
      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
  kv-peer-3:
    build: ../kv-store
    ports:
      - "8083:8083"
    networks:
      - backend
    volumes:
      - kv-peer-3:/var/lib/kvstore/data
    environment:
      KV_STORE_PROTOCOL: "paxos"
      RATIS_KV_PEER_ID: 3
      RATIS_KV_PORT: 8083
      RATIS_KV_PEERS: 1:kv-peer-1:8081,2:kv-peer-2:8082,3:localhost:8083
      RATIS_KV_GROUP_ID: kvStoreRaftGroup
      RATIS_KV_STORAGE_PATH: /var/lib/kvstore/data
volumes:
  kv-peer-1:
  kv-peer-2:
  kv-peer-3:
networks:
  backend:

