version: '3.8'

services:
  k6:
    image: grafana/k6
    container_name: k6_test
    volumes:
      - ./results:/results
      - ./main.js:/test.js
    command: [ "run", "/test.js" ]
    ports:
      - "5665:5665"
    networks:
      - backend
    environment:
      - K6_WEB_DASHBOARD_EXPORT=/results/0326-10ops-5m-raft-7r.html
      - K6_WEB_DASHBOARD=true
      - BASE_URL=http://client:8080
networks:
  backend:
