version: '3.8'

# exp1: 1m: crash, 8m: reboot, crash another

services:
  k6:
    image: grafana/k6
    container_name: k6_test
    volumes:
      - ./results:/results
      - ./main.js:/test.js
    command: [ "run", "/test.js" ]
    ports:
      - "5665:5665"
    networks:
      - backend
    environment:
      - K6_WEB_DASHBOARD_EXPORT=/results/0406-6ops-5m-paxos-3r-25ms_delay-1m_crash.html
      - K6_WEB_DASHBOARD=true
      - BASE_URL=http://client:8080
networks:
  backend:
